export const SET_ZOOM_RATIO = 'SET_ZOOM_RATIO' as const;
export const SET_WIDTH_HEIGHT = 'SET_WIDTH_HEIGHT' as const;
export const SHOW_CROP_HANDLERS = 'SHOW_CROP_HANDLERS' as const;
export const SHOW_PIXELATE_HANDLERS = 'SHOW_PIXELATE_HANDLERS' as const;
export const SET_PIXELATE_HANDLERS_POSITION = 'SET_PIXELATE_HANDLERS_POSITION' as const;
export const SHOW_MINI_HANDLERS = 'SHOW_MINI_HANDLERS' as const;
export const SET_MINI_HANDLERS_HEIGHTS = 'SET_MINI_HANDLERS_HEIGHTS' as const;
